## IN-CLASS: Wages

```{r echo = F}
knitr::opts_chunk$set(eval = FALSE, 
                      warning = FALSE,
                      message = FALSE
                      )
```

### Packages {-}
```{r}
library(tidyverse)
library(knitr)
library(broom)
library(Sleuth3)
```

### Data {-}

```{r}
wages <- case1202 %>% 
  mutate(Female = ifelse(Sex=="Female",1,0)) %>%
  select(-Sal77,-Sex)
```

### Exercises {-}

#### Initial model {-}

```{r}
model <- lm(Bsal ~ Senior + Age + Educ + Exper + Female, 
            data=wages)
tidy(model,conf.int=TRUE)
```

#### Model with mean-centered variables {-}

```{r}
wages <- wages %>%
  mutate(SeniorCent = Senior - mean(Senior), 
         AgeCent = Age-mean(Age), 
         EducCent = Educ - mean(Educ), 
         ExperCent = Exper - mean(Exper))
```

- Fit the regression model using the mean-centered variables. 

```{r}
# regression model with mean-centered variables
```

- How did the model change?

#### Model with indicator variables {-}

- Use the code below to create a categorical variable for `Educ`.

```{r}
wages <- wages %>%
  mutate(EducCat = as.factor(Educ))
```

- Calculate the regression model using `EducCat` instead of `Educ`.

```{r}

```

***